### ISSUE TITLE
MongoEngine's Django User Auth Model Not Supported

### ISSUE THREAD

**Issue by naftulikay** [jazzband/django-mongonaut#59]
Due to a limitation in MongoEngine, User objects stored in MongoEngine don't have a `user_permissions` field, which makes it impossible to log into mongonaut when using MongoEngine's [user model replacement](http://docs.mongoengine.org/en/latest/django.html#custom-user-model):

```
INSTALLED_APPS = (
    ...
    'django.contrib.auth',
    'mongoengine.django.mongo_auth',
    ...
)

AUTH_USER_MODEL = 'mongo_auth.MongoUser'
```

Admittedly, this is a bug in MongoEngine, but it'd be awesome to see a workaround in the meantime in mongonaut to enable users to log in until this is fixed upstream. 

A patch for this would consist of simply replacing the use of the permissions API with a check to `user.is_staff and user.is_active`.

**Comment by shubhambatra** [comment]
solve This issue :+1: 

first Login with 127.0.0.1:8000/admin/
         In case you dont know the user name  and password run :  python manage.py createsuperuser

then go to 127.0.0.1:8000/mongonaut/

**Comment by garrypolley** [comment]
Given the age and new ticket to upgrade to new Django I'm going to close this ticket: #94
