### ISSUE TITLE
Move django-mongonaut to Jazzband.co

### ISSUE THREAD

**Issue by pydanny** [jazzband/django-mongonaut#83]
@garrypolley and I have agreed to move this project to the @jazzband organization. Since we've both been off Mongo DB for several years, maintaining this project ourselves no longer makes sense. By handing this to Jazzband, we are:

1. Putting the project in a place where it will be maintained and extended.
2. Removes the time and effort needed to continue to accept and manage pull requests for a project we no longer wish to maintain but has a somewhat active user base.

I do have some prep work that I'll be doing in the next few days, per the [Jazzband Guidelines](https://jazzband.co/docs/guidelines):

* Add a `contributing.md` document with some Jazzband specified items. I'll probably use someone out of cookiecutter-djangopackage, ported from `.RST` to `.MD` via Pandoc.
* Add a prose description of how to contribute in the Sphinx docs, also likely taken from cookiecutter-djangopackage.
* Add inline documentation, most likely class, method, and function docstrings. Pull requests for this would be nice!

**Comment by jezdez** [comment]
:heart_eyes_cat:

**Comment by jezdez** [comment]
You rock, @pydanny!

**Comment by pydanny** [comment]
Just moved this project over to https://github.com/jazzband/django-mongonaut

:relieved:
